name: wellwave_frontend
description: "wellwave_frontend project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter_health_connect: ^1.2.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/icons/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansThai-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansThai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansThai-Black.ttf
          weight: 900
