name: wellwave_frontend
description: "wellwave_frontend project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.2.3
  flutter_svg: ^2.0.10+1
  step_progress_indicator: ^1.0.2
  image_picker: ^1.1.2
  equatable: ^2.0.5
  http: ^1.2.2
  form_field_validator: ^1.1.0
  confetti: ^0.6.0
  shared_preferences: ^2.5.1
  action_slider: ^0.7.0
  syncfusion_flutter_charts: ^21.1.35
  percent_indicator: ^4.2.2
  flutter_ruler_picker: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/homepage/
    - assets/icons/homepage/assessment/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansThai-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansThai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansThai-Black.ttf
          weight: 900
