name: wellwave_frontend
description: "wellwave_frontend project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter_health_connect: ^1.2.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.2.3
  flutter_svg: ^2.0.10+1
  liquid_progress_indicator: ^0.4.0
  flutter_ruler_picker: ^1.0.6
  calendar_slider: ^0.0.4
  fl_chart: ^0.69.0
  http: ^1.2.2
  intl: ^0.19.0
  equatable: ^2.0.7
  image_picker: ^1.1.2
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  
  

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/icon/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
     - assets/icons/moods_grey/
     - assets/icons/moods_color/
     - assets/icons/water_drop/
     - assets/icons/moon_icon/
     - assets/icons/league/


  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansThai-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansThai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansThai-Black.ttf
          weight: 900
